### ISSUE TITLE
How to expand this to real seismic data?

### ISSUE THREAD

**Issue by YuechuWU1129** [schipp/matched_field_processing_simple#2]
Thanks a lot for sharing your wonderful work, in this logic demo, you place a source somewhere in study region, calculate the cross-correlation density matrix(CSDM) and than calculate beampower of every grid. I want to know, if we use real seismic data, what changes do you want to make to this scripts? eg., how to calculate Green's function spectrum (Suppose we don't have wave velocity information, only seismic noise data)？I am a novice in ambient noise, if you need, I can help you do something I can do to improve this script.
Wish your reply, thanks again!

**Comment by schipp** [comment]
You replace what I called `source_spectra` with spectra computed from real seismograms in line 162 `csdm = get_csdm(spectra=source_spectra)`. For each seismogram you have, you compute simply `np.fft.fft(seismogram)` and put them in a NxM array, with N the number of stations and M the length of each spectrum. This array is the input for CSDM.

For more details, you can refer to e.g., to Umlauft & Korn (2019), where this is explained in equations and more references are given. In that paper, the CSDM is called K.

Umlauft, J., Korn, M. (2019) 3-D fluid channel location from noise tremors using matched field processing. Geophysical Journal International, 219, 1550–1561. doi:10.1093/gji/ggz385

I will also have a different repository ready "soon" that I use for my research and upcoming paper.
